### ISSUE TITLE
using weak cryptography algorithms like MD5 or SHA-1 

### ISSUE THREAD

**Issue by Dris7** [oracle/oci-native-ingress-controller#102]
Using weak cryptography algorithms like MD5 or SHA-1 for sensitive operations such as hash generation, password storage, or secret storage can result in well-known attacks, potentially leading to unauthorized access and data compromise.

https://github.com/oracle/oci-native-ingress-controller/blob/main/vendor/github.com/google/uuid/hash.go

**Comment by nirpai** [comment]
@Dris7 Native Ingress controller does not have any encryption functionality. The only place hash are being used is to generate backend set names which are not cryptographically sensitive.
