### ISSUE TITLE
Is it possible to use the controller with ClusterIP Service type?

### ISSUE THREAD

**Issue by Tarasovych** [oracle/oci-native-ingress-controller#105]
When I'm trying to create a basic Service, controller has these logs
```
I1031 10:30:52.591764       1 util.go:610] Error syncing backends for ingress class default-ingress-class: service default/testecho1 has no nodeports: 
```
So I assume it's not possible to use ClusterIP Services with the controller?

**Comment by piyush-tiwari** [comment]
Hi @Tarasovych, if your cluster's CNI plugin type is Flannel, then it is mandatory to use NodePort type services.

**Comment by Tarasovych** [comment]
Thanks!

**Comment by Tarasovych** [comment]
By the way, what about VCN plugin?

**Comment by piyush-tiwari** [comment]
Yeah, it will work with VCN-Native CNI
