### ISSUE TITLE
Wrong source code for Releases Artifacts v1.1.0 on Helm folder

### ISSUE THREAD

**Issue by tonybolzan** [oracle/oci-native-ingress-controller#18]
Release 1.1.0 has source code for 1.0.0 in Helm folder
https://github.com/oracle/oci-native-ingress-controller/releases/tag/v1.1.0

**Comment by Inbaraj-S** [comment]
Hey @tonybolzan 
Thank you for your valuable feedback. You can use the latest value v1.1.0 in values.yaml during deployment.
Will add a task to update this folder.

**Comment by Inbaraj-S** [comment]
Fixed as part of release V1.2.0.
