### ISSUE TITLE
Feat: Add Access/Error Logs and NSG Options

### ISSUE THREAD

**Issue by tonybolzan** [oracle/oci-native-ingress-controller#19]
Today is not possible to enable NSG and Logs using IngressClassParameters or annotations

**Comment by Inbaraj-S** [comment]
Thank you @tonybolzan. We will look into it.

**Comment by avianabr** [comment]
Nsg support is a must have feature. The new oke Terraform module provided by Oracle uses nsg heavily to implement public and private load balancer access to worker nodes
