### ISSUE TITLE
Feat: Add possibilitie to Listen HTTPS to a Backend in HTTP

### ISSUE THREAD

**Issue by tonybolzan** [oracle/oci-native-ingress-controller#21]
Today, I can have a Listener in HTTPS only if Backend are also in HTTPS.
But are comum to have the LB doing TLS termination, and containers only working with HTTP.

**Comment by Inbaraj-S** [comment]
@tonybolzan 
Do you mean TLS termination at the LB? and not at backend. If so, that feature is in pipeline.

**Comment by robo-cap** [comment]
resolved in PR #44

**Comment by pr07pr07** [comment]
FYI .. Tested this feature with one of our customers today, and it worked as expected. Thank you!
