### ISSUE TITLE
TLS Termination on load balancer

### ISSUE THREAD

**Issue by csraovaradev** [oracle/oci-native-ingress-controller#24]
Since OCI Native ingress controller doesn't support TLS Termination on pod

can we know the steps for TLS termination on pod suing
1. Example for deployment and ingress using OCI certificate
2. Example for deployment and ingress using certs with volume mount

**Comment by Inbaraj-S** [comment]
@csraovaradev 
We support end to end termination.
https://github.com/oracle/oci-native-ingress-controller/blob/main/GettingStarted.md#httpstls-support
