### ISSUE TITLE
does oci-native-ingress-controller support TCP/UDP protocol

### ISSUE THREAD

**Issue by csraovaradev** [oracle/oci-native-ingress-controller#25]
does oci-native-ingress-controller support TCP/UDP protocol in addition to HTTP/HTTPS

**Comment by Inbaraj-S** [comment]
Hi @csraovaradev 
Thank you for reaching out, TCP/UDP support is currently not supported. It is in pipeline.

**Comment by gondaljutt** [comment]
@Inbaraj-S any ETA on this?

**Comment by nirpai** [comment]
Support for TCP listeners released as part of https://github.com/oracle/oci-native-ingress-controller/releases/tag/v1.3.8
