### ISSUE TITLE
The latest version so far does not support the arm64 architecture.

### ISSUE THREAD

**Issue by eyanchao** [oracle/oci-native-ingress-controller#26]
After actual deployment, it was found that the arm64 architecture is not supported. When will the arm64 architecture be supported? Thank you!

**Comment by Inbaraj-S** [comment]
Thank you @eyanchao for reaching out. Yes, Arm architecture is currently not supported, it is in pipeline.

**Comment by eyanchao** [comment]
I particularly look forward to the new version being launched quickly and equipped with the newer k8s version. For example, the k8s version is expected to be 1.28.1. Thank you for your selfless hard work.

**Comment by eyanchao** [comment]
I rebuilt a new image file suitable for the arm64 architecture according to the latest version, which is the dockerfile in v1.2.0. It has been uploaded to the personal image warehouse of dockehub. the name of the image is eyanchao/oci-native-ingress-controller.

Thanks for your selfless open source contribution!

**Comment by Inbaraj-S** [comment]
Included as part of the new release: https://github.com/oracle/oci-native-ingress-controller/releases/tag/v1.3.2
