### ISSUE TITLE
Is waf and custom waf rules now supported?

### ISSUE THREAD

**Issue by eyanchao** [oracle/oci-native-ingress-controller#41]
Thank you for your efforts for the new version, cloud you add support for waf and other features on this basis?

**Comment by Inbaraj-S** [comment]
Hi @eyanchao 
Waf integration is already supported : https://github.com/oracle/oci-native-ingress-controller/blob/main/GettingStarted.md#web-firewall-integration

You can add waf rules to your policies and attach as mentioned in the doc.

**Comment by eyanchao** [comment]
OK, thanks
