### ISSUE TITLE
When I only have one k8s master node on one instance, what the value of cluster_id: in the upper part of the value.yaml file should be 

### ISSUE THREAD

**Issue by eyanchao** [oracle/oci-native-ingress-controller#43]
I only set up the k8s master node on one instance, so when I deployed the oci-native-ingress-controller via helm, I asked what the value of cluster_id: in the upper part of the value.yaml file should be. I found that this value is required. , I have not created OKE cluster yet.

![316d8718eb2073e5b560c303b6d25f7](https://github.com/oracle/oci-native-ingress-controller/assets/10149707/26f2ccde-902c-4c3b-98af-6c91b929c846)

**Comment by avianabr** [comment]
Use the oke ocid listed in the oci console

**Comment by Inbaraj-S** [comment]
@eyanchao 
You would need an OKE cluster and use its OCID here to run the ingress controller.

**Comment by eyanchao** [comment]
Will it be possible to support self-built k8s on oci vm in the future? I have a k8s cluster using microk8s on oci vm.

**Comment by eyanchao** [comment]
> @eyanchao You would need an OKE cluster and use its OCID here to run the ingress controller.

Will it be possible to support self-built k8s on oci vm in the future? I have a k8s cluster using microk8s on oci vm.

**Comment by eyanchao** [comment]
> Use the oke ocid listed in the oci console
Thank you.

**Comment by Inbaraj-S** [comment]
@eyanchao 
> Will it be possible to support self-built k8s on oci vm in the future? I have a k8s cluster using microk8s on them.

Currently not in pipeline.
