### ISSUE TITLE
Default health check port when using the Flannel CNI

### ISSUE THREAD

**Issue by matthewmcdaniel** [oracle/oci-native-ingress-controller#49]
Currently, to use the load balancer health checks effectively when using Flannel, users must manually specify the `healthCheckNodePort` (when using `externalTrafficPolicy: Local`) value and insert that into the Ingress annotations. Many users do not manually specify this value and allow it to be allocated at random. Some users may also want to specify the NodePort of the service and use that for the health check port. Currently, users must track what NodePort the service is running on and insert that into their Ingress annotations.

For example, the OKE CCM defines a default health check port of 10256 when `externalTrafficPolicy` is `Cluster` and a default health check port of `.spec.healthCheckNodePort` when `externalTrafficPolicy` is `Local`.

**Comment by pr07pr07** [comment]
@matthewmcdaniel 
We are currently using Flannel CNI alongside the native ingress controller. According to the documentation, we need to change the service from ClusterIP to NodePort. However, when attempting to manually specify the healthCheckNodePort, we are encountering issues with updating it. Any valuable suggestions from you here .Thank you in advance :-)
