### ISSUE TITLE
WAF Configuration in OKE

### ISSUE THREAD

**Issue by naguaramaster** [oracle/oci-native-ingress-controller#62]
Greetings,

Right now we are configuring WAF in the LoadBalancer that was created with the IngressClass. The Annotation was applied as described in the documentation and when is applied to the IngressClass yaml file, no change is seen in the Load Balancer. We expected it to be associated with the indicated WAF, but it did not happen.
The question remains if there is any special way to apply the IngressClass configuration?
Finally what we did was configure the WAF manually.
Thank you

**Comment by Inbaraj-S** [comment]
@naguaramaster 
could you elaborate on how you set the configuration for WAF policy, ideally you should automatically see the firewall ocid getting attached.
Please share more details.

**Comment by naguaramaster** [comment]
Thank you Ibaraj,

This was solved!
