### ISSUE TITLE
Backends not connected to Load balancer 

### ISSUE THREAD

**Issue by Loobosh** [oracle/oci-native-ingress-controller#64]
Hi. 
I created an OCI native ingress controller following the example in the documentation. The load balancer is created (I can see it in the OCI console) ,but the backend does not connect: error critical-connection failed.

**Comment by nirpai** [comment]
HI @Loobosh, Are the backend sets created as per your ingress declaration? Are the backend status reported healthy? Have you set the required network policies between LB and worker subnets?
