### ISSUE TITLE
Support applying tags to load balancers provisioned by the Native Ingress Controller

### ISSUE THREAD

**Issue by matthewmcdaniel** [oracle/oci-native-ingress-controller#85]
Hi team! Currently, it's not supported to apply defined and freeform tags to load balancers created from an `IngressClass`. This makes it difficult to manage access when using tag-based access control. The CCM currently supports this with two annotations:

`oci.oraclecloud.com/initial-defined-tags-override: '{"<tag-namespace>": {"<tag-key>": "<tag-value>"}}'`

`oci.oraclecloud.com/initial-freeform-tags-override: '{"<tag-key>": "<tag-value>"}'`

https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengcreatingloadbalancer_topic-Summaryofannotations.htm

Would it be possible for the native ingress controller to support this functionality as well?

**Comment by nirpai** [comment]
@matthewmcdaniel Can you please cut a ticket to track this?

**Comment by piyush-tiwari** [comment]
Support for tags has been introduced in v1.4.0
Please check the [release description](https://github.com/oracle/oci-native-ingress-controller/releases/tag/v1.4.0) for details, and upgrade steps.

Closing this issue, feel free to re-open if required.
