### ISSUE TITLE
Controller deletes existing LoadBalancer

### ISSUE THREAD

**Issue by gotsysdba** [oracle/oci-native-ingress-controller#91]
Due to the IngressClassParameters CRD not supporting NSGs, I've tried the annotation route of using an existing LB created by Terraform:

```
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: native-ic-ingress-class
  annotations:
    oci-native-ingress.oraclecloud.com/id: "ocid1.loadbalancer.oc1..."
.
.
.
```

However, when deleting the IngressClass, this also deletes the LoadBalancer created by Terraform (drifting the state).

Expected behaviour:
If the IngressClass is not responsible for creating the LB, it should also not be responsible for deleting it.

**Comment by nirpai** [comment]
@gotsysdba Thanks for reporting the issue. We will look into this.

**Comment by piyush-tiwari** [comment]
@gotsysdba, the `oci-native-ingress.oraclecloud.com/delete-protection-enabled` annotation has been introduced in v1.4.0 to retain LoadBalancers on IngressClass deletion. However, it will be blanked out, i.e., all NSG associations, tags, and WAF associations will be removed from the LB if possible. Please check the [release description](https://github.com/oracle/oci-native-ingress-controller/releases/tag/v1.4.0) for details, and upgrade steps.

Note that NSG support has also been introduced, and you may be better off using NIC to create the LBs too in your use case.

Closing this issue, feel free to re-open if needed.
